//------------------------------------------------------------------------------
// <auto-generated>
//     Kode ini dihasilkan dari template.
//
//     Mengubah file ini secara manual dapat menyebabkan perilaku tidak terduga pada aplikasi.
//     Jika Anda mengubah file ini secara manual, perubahan Anda akan ditimpa saat kode dibuat ulang.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission5Lib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string BookCode { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Author { get; set; }
    }
}
