//------------------------------------------------------------------------------
// <auto-generated>
//     Kode ini dihasilkan dari template.
//
//     Mengubah file ini secara manual dapat menyebabkan perilaku tidak terduga pada aplikasi.
//     Jika Anda mengubah file ini secara manual, perubahan Anda akan ditimpa saat kode dibuat ulang.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission5Lib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopy
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public string BookCopyCode { get; set; }
        public int BookStatus { get; set; }
        public System.DateTime ArrivalDate { get; set; }
    }
}
