//------------------------------------------------------------------------------
// <auto-generated>
//     Kode ini dihasilkan dari template.
//
//     Mengubah file ini secara manual dapat menyebabkan perilaku tidak terduga pada aplikasi.
//     Jika Anda mengubah file ini secara manual, perubahan Anda akan ditimpa saat kode dibuat ulang.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission5Lib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        public int Id { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string PhoneNo { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
    }
}
