//------------------------------------------------------------------------------
// <auto-generated>
//     Kode ini dihasilkan dari template.
//
//     Mengubah file ini secara manual dapat menyebabkan perilaku tidak terduga pada aplikasi.
//     Jika Anda mengubah file ini secara manual, perubahan Anda akan ditimpa saat kode dibuat ulang.
// </auto-generated>
//------------------------------------------------------------------------------

