//------------------------------------------------------------------------------
// <auto-generated>
//     Kode ini dihasilkan dari template.
//
//     Mengubah file ini secara manual dapat menyebabkan perilaku tidak terduga pada aplikasi.
//     Jika Anda mengubah file ini secara manual, perubahan Anda akan ditimpa saat kode dibuat ulang.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission5Lib.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=LibraryDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookCopy> BookCopies { get; set; }
        public virtual DbSet<CheckOut> CheckOuts { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<Member> Members { get; set; }
    }
}
